// Owned by the foundation. Module workstreams import these types; they do not edit this file.

/** Which of the four apps built from this codebase (see app.config.ts / APP_VARIANT). */
export type Variant = 'doctor' | 'staff' | 'owner' | 'patient';
export const VARIANTS: readonly Variant[] = ['doctor', 'staff', 'owner', 'patient'];

/** A screen a module contributes to the mobile apps; Home shows a card for each available one. */
export interface MobileModuleScreen {
  /** Card / header title, e.g. "Today's OPD queue". */
  title: string;
  /** Expo Router path, must live under app/(app)/<moduleKey>/, e.g. "/emr/queue". */
  route: string;
  /** Permission key required to see the screen (e.g. "emr.encounter.read"). Omit for none. */
  permission?: string;
  /**
   * Roles that may see the screen even without `permission`, for modules whose permission keys are
   * not seeded yet. The API still enforces its own permissions on every call.
   */
  roles?: string[];
  /** Apps that include the screen. */
  variants: Variant[];
  /** Optional one-line description shown on the Home card. */
  description?: string;
}

export const MODULE_KEYS = [
  'frontoffice',
  'emr',
  'billing',
  'pharmacy',
  'setup',
  'platform',
  'notifications',
  'reports',
  'portal',
  'lab',
  'radiology',
  'ipd',
  'inventory',
  'insurance',
  'crm',
  'hr',
  'quality',
  'ops',
  'integrations',
] as const;
export type ModuleKey = (typeof MODULE_KEYS)[number];
