import type { emr } from '@hms/shared';

type Icd10Code = emr.Icd10Code;

/**
 * Common OPD diagnoses (ICD-10, WHO 2019). A starter list for search-as-you-type; the full
 * catalogue can replace this later without changing the API.
 */
const RAW: [string, string][] = [
  ['A09', 'Infectious gastroenteritis and colitis, unspecified'],
  ['A01.0', 'Typhoid fever'],
  ['A15.0', 'Tuberculosis of lung'],
  ['A90', 'Dengue fever'],
  ['A91', 'Dengue haemorrhagic fever'],
  ['A92.0', 'Chikungunya virus disease'],
  ['B01.9', 'Varicella without complication'],
  ['B05.9', 'Measles without complication'],
  ['B15.9', 'Hepatitis A without hepatic coma'],
  ['B16.9', 'Acute hepatitis B'],
  ['B20', 'HIV disease'],
  ['B35.4', 'Tinea corporis'],
  ['B35.6', 'Tinea cruris'],
  ['B37.0', 'Candidal stomatitis'],
  ['B50.9', 'Plasmodium falciparum malaria, unspecified'],
  ['B51.9', 'Plasmodium vivax malaria without complication'],
  ['B54', 'Unspecified malaria'],
  ['B82.9', 'Intestinal parasitism, unspecified'],
  ['B86', 'Scabies'],
  ['D50.9', 'Iron deficiency anaemia, unspecified'],
  ['D64.9', 'Anaemia, unspecified'],
  ['E03.9', 'Hypothyroidism, unspecified'],
  ['E05.9', 'Thyrotoxicosis, unspecified'],
  ['E10.9', 'Type 1 diabetes mellitus without complications'],
  ['E11.9', 'Type 2 diabetes mellitus without complications'],
  ['E11.65', 'Type 2 diabetes mellitus with hyperglycaemia'],
  ['E11.4', 'Type 2 diabetes mellitus with neurological complications'],
  ['E55.9', 'Vitamin D deficiency, unspecified'],
  ['E53.8', 'Vitamin B12 deficiency'],
  ['E66.9', 'Obesity, unspecified'],
  ['E78.5', 'Hyperlipidaemia, unspecified'],
  ['E86', 'Volume depletion (dehydration)'],
  ['E87.6', 'Hypokalaemia'],
  ['F32.9', 'Depressive episode, unspecified'],
  ['F41.1', 'Generalized anxiety disorder'],
  ['F41.9', 'Anxiety disorder, unspecified'],
  ['F51.0', 'Nonorganic insomnia'],
  ['G40.9', 'Epilepsy, unspecified'],
  ['G43.9', 'Migraine, unspecified'],
  ['G44.2', 'Tension-type headache'],
  ['G47.0', 'Disorders of initiating and maintaining sleep'],
  ['G56.0', 'Carpal tunnel syndrome'],
  ['H10.9', 'Conjunctivitis, unspecified'],
  ['H52.1', 'Myopia'],
  ['H60.9', 'Otitis externa, unspecified'],
  ['H66.9', 'Otitis media, unspecified'],
  ['H81.1', 'Benign paroxysmal vertigo'],
  ['I10', 'Essential (primary) hypertension'],
  ['I20.9', 'Angina pectoris, unspecified'],
  ['I21.9', 'Acute myocardial infarction, unspecified'],
  ['I25.1', 'Atherosclerotic heart disease'],
  ['I48', 'Atrial fibrillation and flutter'],
  ['I50.9', 'Heart failure, unspecified'],
  ['I63.9', 'Cerebral infarction, unspecified'],
  ['I83.9', 'Varicose veins of lower extremities'],
  ['I84', 'Haemorrhoids'],
  ['J00', 'Acute nasopharyngitis (common cold)'],
  ['J01.9', 'Acute sinusitis, unspecified'],
  ['J02.9', 'Acute pharyngitis, unspecified'],
  ['J03.9', 'Acute tonsillitis, unspecified'],
  ['J06.9', 'Acute upper respiratory infection, unspecified'],
  ['J11.1', 'Influenza with other respiratory manifestations'],
  ['J18.9', 'Pneumonia, unspecified'],
  ['J20.9', 'Acute bronchitis, unspecified'],
  ['J30.4', 'Allergic rhinitis, unspecified'],
  ['J32.9', 'Chronic sinusitis, unspecified'],
  ['J44.9', 'Chronic obstructive pulmonary disease, unspecified'],
  ['J45.9', 'Asthma, unspecified'],
  ['K02.9', 'Dental caries, unspecified'],
  ['K21.9', 'Gastro-oesophageal reflux disease without oesophagitis'],
  ['K25.9', 'Gastric ulcer'],
  ['K29.7', 'Gastritis, unspecified'],
  ['K30', 'Functional dyspepsia'],
  ['K35.8', 'Acute appendicitis, other and unspecified'],
  ['K40.9', 'Inguinal hernia, unspecified'],
  ['K52.9', 'Noninfective gastroenteritis and colitis, unspecified'],
  ['K58.9', 'Irritable bowel syndrome without diarrhoea'],
  ['K59.0', 'Constipation'],
  ['K60.2', 'Anal fissure, unspecified'],
  ['K76.0', 'Fatty (change of) liver, not elsewhere classified'],
  ['K80.2', 'Calculus of gallbladder without cholecystitis'],
  ['L01.0', 'Impetigo'],
  ['L02.9', 'Cutaneous abscess, furuncle and carbuncle, unspecified'],
  ['L20.9', 'Atopic dermatitis, unspecified'],
  ['L23.9', 'Allergic contact dermatitis, unspecified cause'],
  ['L30.9', 'Dermatitis, unspecified'],
  ['L40.9', 'Psoriasis, unspecified'],
  ['L50.9', 'Urticaria, unspecified'],
  ['L70.0', 'Acne vulgaris'],
  ['M17.9', 'Gonarthrosis (knee osteoarthritis), unspecified'],
  ['M19.9', 'Arthrosis, unspecified'],
  ['M06.9', 'Rheumatoid arthritis, unspecified'],
  ['M10.9', 'Gout, unspecified'],
  ['M25.5', 'Pain in joint'],
  ['M54.2', 'Cervicalgia'],
  ['M54.5', 'Low back pain'],
  ['M54.4', 'Lumbago with sciatica'],
  ['M75.0', 'Adhesive capsulitis of shoulder'],
  ['M79.1', 'Myalgia'],
  ['M81.9', 'Osteoporosis, unspecified'],
  ['N18.9', 'Chronic kidney disease, unspecified'],
  ['N20.0', 'Calculus of kidney'],
  ['N30.0', 'Acute cystitis'],
  ['N39.0', 'Urinary tract infection, site not specified'],
  ['N40', 'Hyperplasia of prostate'],
  ['N76.0', 'Acute vaginitis'],
  ['N92.0', 'Excessive and frequent menstruation with regular cycle'],
  ['N94.6', 'Dysmenorrhoea, unspecified'],
  ['N97.9', 'Female infertility, unspecified'],
  ['E28.2', 'Polycystic ovarian syndrome'],
  ['O80', 'Single spontaneous delivery'],
  ['O21.0', 'Mild hyperemesis gravidarum'],
  ['O24.4', 'Diabetes mellitus arising in pregnancy'],
  ['Z34.9', 'Supervision of normal pregnancy, unspecified'],
  ['P59.9', 'Neonatal jaundice, unspecified'],
  ['R05', 'Cough'],
  ['R06.0', 'Dyspnoea'],
  ['R10.4', 'Other and unspecified abdominal pain'],
  ['R11', 'Nausea and vomiting'],
  ['R42', 'Dizziness and giddiness'],
  ['R50.9', 'Fever, unspecified'],
  ['R51', 'Headache'],
  ['R53', 'Malaise and fatigue'],
  ['R07.4', 'Chest pain, unspecified'],
  ['R73.0', 'Abnormal glucose tolerance test (prediabetes)'],
  ['S00.9', 'Superficial injury of head, unspecified'],
  ['S52.5', 'Fracture of lower end of radius'],
  ['S61.9', 'Open wound of wrist and hand, unspecified'],
  ['S93.4', 'Sprain and strain of ankle'],
  ['T14.0', 'Superficial injury of unspecified body region'],
  ['T30.0', 'Burn of unspecified body region, unspecified degree'],
  ['T63.0', 'Toxic effect of snake venom'],
  ['T78.4', 'Allergy, unspecified'],
  ['W54', 'Bitten or struck by dog'],
  ['Z00.0', 'General medical examination'],
  ['Z01.0', 'Examination of eyes and vision'],
  ['Z02.7', 'Issue of medical certificate'],
  ['Z09', 'Follow-up examination after treatment'],
  ['Z23', 'Need for immunization'],
  ['Z30.0', 'General counselling and advice on contraception'],
  ['U07.1', 'COVID-19, virus identified'],
];

export const ICD10_COMMON: readonly Icd10Code[] = RAW.map(([code, description]) => ({ code, description }));

export function searchIcd10(q: string, limit = 20): Icd10Code[] {
  const term = q.trim().toLowerCase();
  if (!term) return ICD10_COMMON.slice(0, limit);
  const byCode = ICD10_COMMON.filter((c) => c.code.toLowerCase().startsWith(term));
  const words = term.split(/\s+/);
  const byText = ICD10_COMMON.filter((c) => !byCode.includes(c) && words.every((w) => c.description.toLowerCase().includes(w)));
  return [...byCode, ...byText].slice(0, limit);
}
